import type { Spot } from "./types";

export const SPOTS: Spot[] = [
  {
    id: "tarifa",
    name: "Tarifa",
    country: "Spain",
    region: "Worldwide",
    lat: 36.0128,
    lon: -5.6012,
    onshoreWindDir: 180,
    blurb: "Levante (E) and Poniente (W) both blow cross-shore here — the classic wind capital of Europe.",
    metarStation: { icao: "LXGB", name: "Gibraltar Airport", lat: 36.151, lon: -5.35 },
  },
  {
    id: "bloubergstrand",
    name: "Bloubergstrand",
    country: "South Africa",
    region: "Worldwide",
    lat: -33.8567,
    lon: 18.4775,
    onshoreWindDir: 280,
    blurb: "The Cape Doctor (SE) blows cross-offshore under Table Mountain — reliable strong summer wind.",
    metarStation: { icao: "FACT", name: "Cape Town Intl Airport", lat: -33.965, lon: 18.602 },
  },
  {
    id: "kanaha",
    name: "Kanaha Beach",
    country: "USA (Maui)",
    region: "Worldwide",
    lat: 20.905,
    lon: -156.43,
    onshoreWindDir: 0,
    blurb: "NE trade winds blow cross-onshore across the north shore — one of the world's best all-round spots.",
    metarStation: { icao: "PHOG", name: "Kahului Airport", lat: 20.8887, lon: -156.4345 },
  },
  {
    id: "cabarete",
    name: "Cabarete",
    country: "Dominican Republic",
    region: "Worldwide",
    lat: 19.758,
    lon: -70.409,
    onshoreWindDir: 0,
    blurb: "Afternoon thermal wind (ENE) builds cross-onshore over a bay ringed by launch-friendly beaches.",
    metarStation: { icao: "MDPP", name: "Puerto Plata Airport", lat: 19.759, lon: -70.571 },
  },
  {
    id: "jericoacoara",
    name: "Jericoacoara",
    country: "Brazil",
    region: "Worldwide",
    lat: -2.7975,
    lon: -40.5137,
    onshoreWindDir: 0,
    blurb: "Consistent SE trade winds blow cross-shore across flat lagoons and open ocean beach breaks.",
  },
  {
    id: "dakhla",
    name: "Dakhla Lagoon",
    country: "Morocco",
    region: "Worldwide",
    lat: 23.68,
    lon: -15.95,
    onshoreWindDir: 315,
    blurb: "Flat-water desert lagoon with strong, steady NE trade winds nearly year-round.",
    metarStation: { icao: "GMMH", name: "Dakhla Airport", lat: 23.718, lon: -15.932 },
  },
  {
    id: "hood-river",
    name: "Hood River",
    country: "USA (Oregon)",
    region: "Worldwide",
    lat: 45.7,
    lon: -121.52,
    onshoreWindDir: 90,
    blurb: "Thermal wind funnels along the Columbia River Gorge, flanked by land on both sides.",
    metarStation: { icao: "KDLS", name: "The Dalles Municipal Airport", lat: 45.619, lon: -121.1657 },
  },
  {
    id: "essaouira",
    name: "Essaouira",
    country: "Morocco",
    region: "Worldwide",
    lat: 31.512,
    lon: -9.77,
    onshoreWindDir: 270,
    blurb: "The 'Wind City of Africa' — strong NE trade-driven cross-shore wind almost daily.",
    metarStation: { icao: "GMMI", name: "Essaouira/Mogador Airport", lat: 31.406, lon: -9.687 },
  },
  {
    id: "pervolia",
    name: "Pervolia",
    country: "Cyprus",
    region: "Cyprus",
    lat: 34.865,
    lon: 33.635,
    onshoreWindDir: 170,
    blurb: "South-coast beach near Larnaca that picks up steady summer southerlies and the afternoon sea breeze.",
    metarStation: { icao: "LCLK", name: "Larnaca Intl Airport", lat: 34.874, lon: 33.617 },
  },
  {
    id: "akrotiri",
    name: "Akrotiri",
    country: "Cyprus",
    region: "Cyprus",
    lat: 34.593,
    lon: 32.939,
    onshoreWindDir: 170,
    blurb: "Open south-facing beach on the Akrotiri peninsula, exposed to the Mediterranean's prevailing summer wind.",
    metarStation: { icao: "LCRA", name: "RAF Akrotiri", lat: 34.59, lon: 32.988 },
  },
  {
    id: "ladies-mile",
    name: "Ladies Mile",
    country: "Cyprus",
    region: "Cyprus",
    lat: 34.648,
    lon: 33.009,
    onshoreWindDir: 120,
    blurb: "Long, flat-water beach on the Limassol side of the Akrotiri peninsula — a forgiving cross-shore learning spot.",
    metarStation: { icao: "LCRA", name: "RAF Akrotiri", lat: 34.59, lon: 32.988 },
  },
  {
    id: "paramali",
    name: "Paramali",
    country: "Cyprus",
    region: "Cyprus",
    lat: 34.667,
    lon: 32.807,
    onshoreWindDir: 170,
    blurb: "Quieter south-coast spot between Limassol and Pissouri with a wide, uncrowded launch.",
    metarStation: { icao: "LCRA", name: "RAF Akrotiri", lat: 34.59, lon: 32.988 },
  },
  {
    id: "karavostasi",
    name: "Karavostasi (Yeşilyurt)",
    country: "Cyprus (north coast)",
    region: "Cyprus",
    lat: 35.148,
    lon: 32.823,
    onshoreWindDir: 330,
    blurb: "Faces Morphou Bay on Cyprus's north coast, catching the Etesian northerlies that dominate the eastern Med in summer.",
  },
  {
    id: "prasonisi",
    name: "Prasonisi",
    country: "Greece (Rhodes)",
    region: "Greece",
    lat: 35.8825,
    lon: 27.7592,
    onshoreWindDir: 270,
    blurb: "The sandy spit at Rhodes's southern tip splits two seas — flat-water lagoon on one side, waves on the other, both lit up by the summer meltemi.",
  },
  {
    id: "mykonos-ftelia",
    name: "Ftelia Beach",
    country: "Greece (Mykonos)",
    region: "Greece",
    lat: 37.478,
    lon: 25.36,
    onshoreWindDir: 0,
    blurb: "Mykonos's dedicated kite bay — a north-facing hook that takes the meltemi almost straight onshore, choppy but relentlessly windy.",
    metarStation: { icao: "LGMK", name: "Mykonos Airport", lat: 37.435, lon: 25.348 },
  },
  {
    id: "paros-golden-beach",
    name: "Golden Beach",
    country: "Greece (Paros)",
    region: "Greece",
    lat: 37.033,
    lon: 25.183,
    onshoreWindDir: 90,
    blurb: "East-coast Cyclades spot that's hosted world-cup freestyle events — cross-shore meltemi over a wide sandy bay.",
    metarStation: { icao: "LGPA", name: "Paros Airport", lat: 37.022, lon: 25.114 },
  },
  {
    id: "brouwersdam",
    name: "Brouwersdam",
    country: "Netherlands",
    region: "Netherlands",
    lat: 51.751,
    lon: 3.838,
    onshoreWindDir: 280,
    blurb: "The Dutch kite mecca — a causeway with open-sea waves on the North Sea side and flat water on the Grevelingen lagoon side.",
  },
  {
    id: "ijmuiden",
    name: "IJmuiden",
    country: "Netherlands",
    region: "Netherlands",
    lat: 52.468,
    lon: 4.552,
    onshoreWindDir: 270,
    blurb: "A go-to North Sea beach near Amsterdam, busy whenever a westerly blows in.",
    metarStation: { icao: "EHAM", name: "Amsterdam Schiphol Airport", lat: 52.315, lon: 4.79 },
  },
  {
    id: "scheveningen",
    name: "Scheveningen",
    country: "Netherlands",
    region: "Netherlands",
    lat: 52.108,
    lon: 4.278,
    onshoreWindDir: 290,
    blurb: "Den Haag's city beach — easy access and steady North Sea wind right by the pier.",
    metarStation: { icao: "EHRD", name: "Rotterdam The Hague Airport", lat: 51.954, lon: 4.444 },
  },
];

const REGION_ORDER = ["Worldwide", "Cyprus", "Greece", "Netherlands"];

/** Spots grouped by sidebar region, with `REGION_ORDER` pinned first and any other region alphabetical after. */
export const SPOT_GROUPS: [string, Spot[]][] = (() => {
  const groups = new Map<string, Spot[]>();
  for (const spot of SPOTS) {
    if (!groups.has(spot.region)) groups.set(spot.region, []);
    groups.get(spot.region)!.push(spot);
  }
  return [...groups.entries()].sort(([a], [b]) => {
    const ia = REGION_ORDER.indexOf(a);
    const ib = REGION_ORDER.indexOf(b);
    if (ia === -1 && ib === -1) return a.localeCompare(b);
    if (ia === -1) return 1;
    if (ib === -1) return -1;
    return ia - ib;
  });
})();
