import type { Spot } from "./types";

export const SPOTS: Spot[] = [
  {
    id: "tarifa",
    name: "Tarifa",
    country: "Spain",
    lat: 36.0128,
    lon: -5.6012,
    onshoreWindDir: 180,
    blurb: "Levante (E) and Poniente (W) both blow cross-shore here — the classic wind capital of Europe.",
  },
  {
    id: "bloubergstrand",
    name: "Bloubergstrand",
    country: "South Africa",
    lat: -33.8567,
    lon: 18.4775,
    onshoreWindDir: 280,
    blurb: "The Cape Doctor (SE) blows cross-offshore under Table Mountain — reliable strong summer wind.",
  },
  {
    id: "kanaha",
    name: "Kanaha Beach",
    country: "USA (Maui)",
    lat: 20.905,
    lon: -156.43,
    onshoreWindDir: 0,
    blurb: "NE trade winds blow cross-onshore across the north shore — one of the world's best all-round spots.",
  },
  {
    id: "cabarete",
    name: "Cabarete",
    country: "Dominican Republic",
    lat: 19.758,
    lon: -70.409,
    onshoreWindDir: 0,
    blurb: "Afternoon thermal wind (ENE) builds cross-onshore over a bay ringed by launch-friendly beaches.",
  },
  {
    id: "jericoacoara",
    name: "Jericoacoara",
    country: "Brazil",
    lat: -2.7975,
    lon: -40.5137,
    onshoreWindDir: 0,
    blurb: "Consistent SE trade winds blow cross-shore across flat lagoons and open ocean beach breaks.",
  },
  {
    id: "dakhla",
    name: "Dakhla Lagoon",
    country: "Morocco",
    lat: 23.68,
    lon: -15.95,
    onshoreWindDir: 315,
    blurb: "Flat-water desert lagoon with strong, steady NE trade winds nearly year-round.",
  },
  {
    id: "hood-river",
    name: "Hood River",
    country: "USA (Oregon)",
    lat: 45.7,
    lon: -121.52,
    onshoreWindDir: 90,
    blurb: "Thermal wind funnels along the Columbia River Gorge, flanked by land on both sides.",
  },
  {
    id: "essaouira",
    name: "Essaouira",
    country: "Morocco",
    lat: 31.512,
    lon: -9.77,
    onshoreWindDir: 270,
    blurb: "The 'Wind City of Africa' — strong NE trade-driven cross-shore wind almost daily.",
  },
  {
    id: "pervolia",
    name: "Pervolia",
    country: "Cyprus",
    lat: 34.865,
    lon: 33.635,
    onshoreWindDir: 170,
    blurb: "South-coast beach near Larnaca that picks up steady summer southerlies and the afternoon sea breeze.",
  },
  {
    id: "akrotiri",
    name: "Akrotiri",
    country: "Cyprus",
    lat: 34.593,
    lon: 32.939,
    onshoreWindDir: 170,
    blurb: "Open south-facing beach on the Akrotiri peninsula, exposed to the Mediterranean's prevailing summer wind.",
  },
  {
    id: "ladies-mile",
    name: "Ladies Mile",
    country: "Cyprus",
    lat: 34.648,
    lon: 33.009,
    onshoreWindDir: 120,
    blurb: "Long, flat-water beach on the Limassol side of the Akrotiri peninsula — a forgiving cross-shore learning spot.",
  },
  {
    id: "paramali",
    name: "Paramali",
    country: "Cyprus",
    lat: 34.667,
    lon: 32.807,
    onshoreWindDir: 170,
    blurb: "Quieter south-coast spot between Limassol and Pissouri with a wide, uncrowded launch.",
  },
  {
    id: "karavostasi",
    name: "Karavostasi (Yeşilyurt)",
    country: "Cyprus (north coast)",
    lat: 35.148,
    lon: 32.823,
    onshoreWindDir: 330,
    blurb: "Faces Morphou Bay on Cyprus's north coast, catching the Etesian northerlies that dominate the eastern Med in summer.",
  },
];
