import type { AppMode, Spot } from "./types";

export const SPOTS: Spot[] = [
  {
    id: "tarifa",
    name: "Tarifa",
    country: "Spain",
    region: "Worldwide",
    sports: ["kite", "surf"],
    lat: 36.0128,
    lon: -5.6012,
    onshoreWindDir: 180,
    facingDir: 220,
    breakType: "Beach Break",
    blurb: "Levante (E) and Poniente (W) both blow cross-shore here — the classic wind capital of Europe.",
    surfBlurb: "Exposed Atlantic beach break receiving Atlantic westerlies and Poniente swells.",
    metarStation: { icao: "LXGB", name: "Gibraltar Airport", lat: 36.151, lon: -5.35 },
  },
  {
    id: "bloubergstrand",
    name: "Bloubergstrand",
    country: "South Africa",
    region: "Worldwide",
    sports: ["kite", "surf"],
    lat: -33.8567,
    lon: 18.4775,
    onshoreWindDir: 280,
    facingDir: 270,
    breakType: "Beach Break",
    blurb: "The Cape Doctor (SE) blows cross-offshore under Table Mountain — reliable strong summer wind.",
    surfBlurb: "Heavy Atlantic beachbreak picking up raw SW swells with SE offshore wind.",
    metarStation: { icao: "FACT", name: "Cape Town Intl Airport", lat: -33.965, lon: 18.602 },
  },
  {
    id: "kanaha",
    name: "Kanaha Beach",
    country: "USA (Maui)",
    region: "Worldwide",
    sports: ["kite", "surf"],
    lat: 20.905,
    lon: -156.43,
    onshoreWindDir: 0,
    facingDir: 0,
    breakType: "Reef Break",
    blurb: "NE trade winds blow cross-onshore across the north shore — one of the world's best all-round spots.",
    surfBlurb: "Maui North Shore outer reef break catching big NW winter swells.",
    metarStation: { icao: "PHOG", name: "Kahului Airport", lat: 20.8887, lon: -156.4345 },
  },
  {
    id: "cabarete",
    name: "Cabarete",
    country: "Dominican Republic",
    region: "Worldwide",
    sports: ["kite", "surf"],
    lat: 19.758,
    lon: -70.409,
    onshoreWindDir: 0,
    facingDir: 0,
    breakType: "Reef Break",
    blurb: "Afternoon thermal wind (ENE) builds cross-onshore over a bay ringed by launch-friendly beaches.",
    surfBlurb: "Outer reef breaks pick up clean N Atlantic winter swells.",
    metarStation: { icao: "MDPP", name: "Puerto Plata Airport", lat: 19.759, lon: -70.571 },
  },
  {
    id: "jericoacoara",
    name: "Jericoacoara",
    country: "Brazil",
    region: "Worldwide",
    sports: ["kite"],
    lat: -2.7975,
    lon: -40.5137,
    onshoreWindDir: 0,
    facingDir: 0,
    breakType: "Point Break",
    blurb: "Consistent SE trade winds blow cross-shore across flat lagoons and open ocean beach breaks.",
    surfBlurb: "Gentle longboard waves off the sand point on NE ocean swells.",
  },
  {
    id: "dakhla",
    name: "Dakhla Lagoon",
    country: "Morocco",
    region: "Worldwide",
    sports: ["kite"],
    lat: 23.68,
    lon: -15.95,
    onshoreWindDir: 315,
    facingDir: 315,
    breakType: "Point Break",
    blurb: "Flat-water desert lagoon with strong, steady NE trade winds nearly year-round.",
    surfBlurb: "Oassou and Westpoint ocean side pointbreaks offering long right handers.",
    metarStation: { icao: "GMMH", name: "Dakhla Airport", lat: 23.718, lon: -15.932 },
  },
  {
    id: "hood-river",
    name: "Hood River",
    country: "USA (Oregon)",
    region: "Worldwide",
    sports: ["kite"],
    lat: 45.7,
    lon: -121.52,
    onshoreWindDir: 90,
    facingDir: 90,
    breakType: "Beach Break",
    blurb: "Thermal wind funnels along the Columbia River Gorge, flanked by land on both sides.",
    surfBlurb: "Freshwater river swell created by strong thermal wind against current.",
    metarStation: { icao: "KDLS", name: "The Dalles Municipal Airport", lat: 45.619, lon: -121.1657 },
  },
  {
    id: "essaouira",
    name: "Essaouira",
    country: "Morocco",
    region: "Worldwide",
    sports: ["kite", "surf"],
    lat: 31.512,
    lon: -9.77,
    onshoreWindDir: 270,
    facingDir: 270,
    breakType: "Beach Break",
    blurb: "The 'Wind City of Africa' — strong NE trade-driven cross-shore wind almost daily.",
    surfBlurb: "Wide sandy beach break and bay reefs catching Atlantic groundswells.",
    metarStation: { icao: "GMMI", name: "Essaouira/Mogador Airport", lat: 31.406, lon: -9.687 },
  },
  // --- Cyprus Spots ---
  {
    id: "paphos-venus",
    name: "Venus Beach (Paphos)",
    country: "Cyprus",
    region: "Cyprus",
    sports: ["surf"],
    lat: 34.7801,
    lon: 32.4045,
    onshoreWindDir: 270,
    facingDir: 270,
    optimalSwellMinDeg: 210,
    optimalSwellMaxDeg: 310,
    breakType: "Reef Break",
    optimalTide: "all",
    blurb: "West-facing Paphos coast exposed to open Mediterranean swells.",
    surfBlurb: "Paphos's premier surf spot — reef break taking W-SW winter groundswells with clean E offshore wind.",
    metarStation: { icao: "PFO", name: "Paphos Intl Airport", lat: 34.718, lon: 32.485 },
  },
  {
    id: "coral-bay-helios",
    name: "Helios / Coral Bay",
    country: "Cyprus",
    region: "Cyprus",
    sports: ["surf"],
    lat: 34.8542,
    lon: 32.3688,
    onshoreWindDir: 240,
    facingDir: 240,
    optimalSwellMinDeg: 200,
    optimalSwellMaxDeg: 280,
    breakType: "Beach Break",
    optimalTide: "mid",
    blurb: "SW-facing cove north of Paphos with clean sandbars.",
    surfBlurb: "Sheltered bay near Coral Bay that holds fun lefts on medium SW swells with N/NE offshore winds.",
    metarStation: { icao: "PFO", name: "Paphos Intl Airport", lat: 34.718, lon: 32.485 },
  },
  {
    id: "curium",
    name: "Curium Beach (Kourion)",
    country: "Cyprus",
    region: "Cyprus",
    sports: ["kite", "surf"],
    lat: 34.6644,
    lon: 32.8872,
    onshoreWindDir: 180,
    facingDir: 180,
    optimalSwellMinDeg: 160,
    optimalSwellMaxDeg: 240,
    breakType: "Beach Break",
    optimalTide: "all",
    blurb: "Open south-facing bay under the ancient Kourion amphitheatre.",
    surfBlurb: "Limassol's main south coast surf break. Best on strong S/SW storm swells with N offshore wind.",
    metarStation: { icao: "LCRA", name: "RAF Akrotiri", lat: 34.59, lon: 32.988 },
  },
  {
    id: "alaminos",
    name: "Alaminos Reef",
    country: "Cyprus",
    region: "Cyprus",
    sports: ["surf"],
    lat: 34.7335,
    lon: 33.4312,
    onshoreWindDir: 150,
    facingDir: 150,
    optimalSwellMinDeg: 130,
    optimalSwellMaxDeg: 210,
    breakType: "Reef Break",
    optimalTide: "mid",
    blurb: "SE-facing coast between Limassol and Larnaca.",
    surfBlurb: "Larnaca reef break providing clean peelers on S/SE Med swells with NW offshore wind.",
    metarStation: { icao: "LCLK", name: "Larnaca Intl Airport", lat: 34.874, lon: 33.617 },
  },
  {
    id: "cape-greco",
    name: "Cape Greco / Konnos",
    country: "Cyprus",
    region: "Cyprus",
    sports: ["surf"],
    lat: 34.9841,
    lon: 34.0711,
    onshoreWindDir: 110,
    facingDir: 110,
    optimalSwellMinDeg: 70,
    optimalSwellMaxDeg: 150,
    breakType: "Point Break",
    optimalTide: "high",
    blurb: "East coast rocky point near Ayia Napa.",
    surfBlurb: "Ayia Napa eastern point break that catches easterly storm swells with W offshore winds.",
    metarStation: { icao: "LCLK", name: "Larnaca Intl Airport", lat: 34.874, lon: 33.617 },
  },
  {
    id: "pervolia",
    name: "Pervolia",
    country: "Cyprus",
    region: "Cyprus",
    sports: ["kite"],
    lat: 34.865,
    lon: 33.635,
    onshoreWindDir: 170,
    facingDir: 170,
    breakType: "Beach Break",
    blurb: "South-coast beach near Larnaca that picks up steady summer southerlies and the afternoon sea breeze.",
    surfBlurb: "South Larnaca beach break picking up southerly wind swells.",
    metarStation: { icao: "LCLK", name: "Larnaca Intl Airport", lat: 34.874, lon: 33.617 },
  },
  {
    id: "akrotiri",
    name: "Akrotiri",
    country: "Cyprus",
    region: "Cyprus",
    sports: ["kite"],
    lat: 34.593,
    lon: 32.939,
    onshoreWindDir: 170,
    facingDir: 170,
    breakType: "Beach Break",
    blurb: "Open south-facing beach on the Akrotiri peninsula, exposed to the Mediterranean's prevailing summer wind.",
    surfBlurb: "South Akrotiri bay picking up open Mediterranean S/SW swells.",
    metarStation: { icao: "LCRA", name: "RAF Akrotiri", lat: 34.59, lon: 32.988 },
  },
  {
    id: "ladies-mile",
    name: "Ladies Mile",
    country: "Cyprus",
    region: "Cyprus",
    sports: ["kite"],
    lat: 34.648,
    lon: 33.009,
    onshoreWindDir: 120,
    facingDir: 120,
    breakType: "Beach Break",
    blurb: "Long, flat-water beach on the Limassol side of the Akrotiri peninsula — a forgiving cross-shore learning spot.",
    surfBlurb: "Protected Limassol bay with gentle waves on SE swells.",
    metarStation: { icao: "LCRA", name: "RAF Akrotiri", lat: 34.59, lon: 32.988 },
  },
  {
    id: "paramali",
    name: "Paramali",
    country: "Cyprus",
    region: "Cyprus",
    sports: ["kite", "surf"],
    lat: 34.667,
    lon: 32.807,
    onshoreWindDir: 170,
    facingDir: 170,
    breakType: "Beach Break",
    blurb: "Quieter south-coast spot between Limassol and Pissouri with a wide, uncrowded launch.",
    surfBlurb: "Wide beach break picking up south Mediterranean swell.",
    metarStation: { icao: "LCRA", name: "RAF Akrotiri", lat: 34.59, lon: 32.988 },
  },
  {
    id: "karavostasi",
    name: "Karavostasi (Yeşilyurt)",
    country: "Cyprus (north coast)",
    region: "Cyprus",
    sports: ["kite", "surf"],
    lat: 35.148,
    lon: 32.823,
    onshoreWindDir: 330,
    facingDir: 330,
    breakType: "Beach Break",
    blurb: "Faces Morphou Bay on Cyprus's north coast, catching the Etesian northerlies that dominate the eastern Med in summer.",
    surfBlurb: "North coast Morphou Bay catching N/NW wind swells.",
  },
  {
    id: "prasonisi",
    name: "Prasonisi",
    country: "Greece (Rhodes)",
    region: "Greece",
    sports: ["kite", "surf"],
    lat: 35.8825,
    lon: 27.7592,
    onshoreWindDir: 270,
    facingDir: 270,
    breakType: "Beach Break",
    blurb: "The sandy spit at Rhodes's southern tip splits two seas — flat-water lagoon on one side, waves on the other, both lit up by the summer meltemi.",
  },
  {
    id: "mykonos-ftelia",
    name: "Ftelia Beach",
    country: "Greece (Mykonos)",
    region: "Greece",
    sports: ["kite"],
    lat: 37.478,
    lon: 25.36,
    onshoreWindDir: 0,
    facingDir: 0,
    breakType: "Beach Break",
    blurb: "Mykonos's dedicated kite bay — a north-facing hook that takes the meltemi almost straight onshore, choppy but relentlessly windy.",
    metarStation: { icao: "LGMK", name: "Mykonos Airport", lat: 37.435, lon: 25.348 },
  },
  {
    id: "paros-golden-beach",
    name: "Golden Beach",
    country: "Greece (Paros)",
    region: "Greece",
    sports: ["kite"],
    lat: 37.033,
    lon: 25.183,
    onshoreWindDir: 90,
    facingDir: 90,
    breakType: "Beach Break",
    blurb: "East-coast Cyclades spot that's hosted world-cup freestyle events — cross-shore meltemi over a wide sandy bay.",
    metarStation: { icao: "LGPA", name: "Paros Airport", lat: 37.022, lon: 25.114 },
  },
  {
    id: "brouwersdam",
    name: "Brouwersdam",
    country: "Netherlands",
    region: "Netherlands",
    sports: ["kite"],
    lat: 51.751,
    lon: 3.838,
    onshoreWindDir: 280,
    facingDir: 280,
    breakType: "Beach Break",
    blurb: "The Dutch kite mecca — a causeway with open-sea waves on the North Sea side and flat water on the Grevelingen lagoon side.",
  },
  {
    id: "ijmuiden",
    name: "IJmuiden",
    country: "Netherlands",
    region: "Netherlands",
    sports: ["kite", "surf"],
    lat: 52.468,
    lon: 4.552,
    onshoreWindDir: 270,
    facingDir: 270,
    breakType: "Beach Break",
    blurb: "A go-to North Sea beach near Amsterdam, busy whenever a westerly blows in.",
    metarStation: { icao: "EHAM", name: "Amsterdam Schiphol Airport", lat: 52.315, lon: 4.79 },
  },
  {
    id: "scheveningen",
    name: "Scheveningen",
    country: "Netherlands",
    region: "Netherlands",
    sports: ["kite", "surf"],
    lat: 52.108,
    lon: 4.278,
    onshoreWindDir: 290,
    facingDir: 290,
    breakType: "Beach Break",
    blurb: "Den Haag's city beach — easy access and steady North Sea wind right by the pier.",
    metarStation: { icao: "EHRD", name: "Rotterdam The Hague Airport", lat: 51.954, lon: 4.444 },
  },
];

const REGION_ORDER = ["Worldwide", "Cyprus", "Greece", "Netherlands"];

export function getSpotsForMode(mode: AppMode): Spot[] {
  return SPOTS.filter((s) => !s.sports || s.sports.includes(mode));
}

/** Spots grouped by sidebar region for a given sport mode, with `REGION_ORDER` pinned first. */
export function getSpotGroupsForMode(mode: AppMode): [string, Spot[]][] {
  const modeSpots = getSpotsForMode(mode);
  const groups = new Map<string, Spot[]>();
  for (const spot of modeSpots) {
    if (!groups.has(spot.region)) groups.set(spot.region, []);
    groups.get(spot.region)!.push(spot);
  }
  return [...groups.entries()].sort(([a], [b]) => {
    const ia = REGION_ORDER.indexOf(a);
    const ib = REGION_ORDER.indexOf(b);
    if (ia === -1 && ib === -1) return a.localeCompare(b);
    if (ia === -1) return 1;
    if (ib === -1) return -1;
    return ia - ib;
  });
}

/** Backward compatible default grouping */
export const SPOT_GROUPS: [string, Spot[]][] = getSpotGroupsForMode("kite");
